service: cart-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: 'eu-west-1'
  iam:
    role: arn:aws:iam::295974408458:role/RDSRole

plugins:
  - serverless-offline

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'